import { Flavor } from "@/components/FlavorCard";

export const flavors: Flavor[] = [
  {
    id: 1,
    name: "Stracciatella",
    description: "Creamy milk gelato with rich dark chocolate shavings folded throughout.",
    category: "Classic",
    color: "#F4C5C0",
    emoji: "🍫",
    allergens: ["milk", "soy"],
  },
  {
    id: 2,
    name: "Pistachio di Bronte",
    description: "Sicilian pistachios blended into a silky, intensely nutty gelato.",
    category: "Classic",
    color: "#A8C5A0",
    emoji: "🫘",
    allergens: ["milk", "nuts"],
  },
  {
    id: 3,
    name: "Fior di Latte",
    description: "The purest expression of gelato — sweet cream, nothing more.",
    category: "Classic",
    color: "#FFF8F0",
    emoji: "🥛",
    glutenFree: true,
    allergens: ["milk"],
  },
  {
    id: 4,
    name: "Tiramisù",
    description: "Espresso-soaked ladyfingers meet mascarpone in frozen form.",
    category: "Classic",
    color: "#D4A853",
    emoji: "☕",
    allergens: ["milk", "eggs", "gluten"],
  },
  {
    id: 5,
    name: "Mango Passion",
    description: "Sun-ripened Alphonso mango with a hint of passion fruit zing.",
    category: "Sorbet",
    color: "#FFD580",
    emoji: "🥭",
    vegan: true,
    glutenFree: true,
  },
  {
    id: 6,
    name: "Wild Strawberry",
    description: "Alpine strawberries at peak ripeness, blended into a vibrant sorbet.",
    category: "Sorbet",
    color: "#F4C5C0",
    emoji: "🍓",
    vegan: true,
    glutenFree: true,
  },
  {
    id: 7,
    name: "Lemon Basil",
    description: "Amalfi lemons brightened with fresh garden basil. Unexpected and perfect.",
    category: "Sorbet",
    color: "#E8F0A0",
    emoji: "🍋",
    vegan: true,
    glutenFree: true,
  },
  {
    id: 8,
    name: "Oat Milk Chocolate",
    description: "Deeply chocolatey, totally plant-based, and incredibly indulgent.",
    category: "Vegan",
    color: "#C9A880",
    emoji: "🍪",
    vegan: true,
    glutenFree: true,
  },
  {
    id: 9,
    name: "Coconut & Lime",
    description: "Tropical coconut cream with a zesty lime finish. Summer in a cup.",
    category: "Vegan",
    color: "#A8D8C0",
    emoji: "🥥",
    vegan: true,
    glutenFree: true,
  },
  {
    id: 10,
    name: "Fig & Honey",
    description: "Late-season figs paired with wildflower honey. A seasonal favourite.",
    category: "Seasonal",
    color: "#C9B8D8",
    emoji: "🫐",
    allergens: ["milk"],
  },
  {
    id: 11,
    name: "Pumpkin Spice",
    description: "Roasted pumpkin with cinnamon, nutmeg, and a touch of ginger.",
    category: "Seasonal",
    color: "#E8A870",
    emoji: "🎃",
    allergens: ["milk"],
  },
  {
    id: 12,
    name: "Rose & Raspberry",
    description: "Delicate Damascus rose water with fresh Scottish raspberries.",
    category: "Seasonal",
    color: "#F4A0B0",
    emoji: "🌹",
    vegan: true,
    glutenFree: true,
  },
];
